### ISSUE TITLE
Create basic Getting Started wiki page

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/tsofa#4]
The page should explain how to get started with development for new users.

**Comment by lcabrini** [comment]
I have done this. Please follow the instructions. If all works, let's close this issue.

**Comment by Prince-linux** [comment]
can you send me the link to the  wiki please??

**Comment by lcabrini** [comment]
https://github.com/lcabrini/tsofa/wiki/How-to-get-started-with-development

**Comment by Prince-linux** [comment]
+1
