### ISSUE TITLE
Move all files from laravel directory into tsofa

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/tsofa#8]
We seem to have conflicting directory structures. The project directory was called laravel, but I changed it to tsofa instead. However, new files are still being created in laravel. 

It is important that after this change, everybody does a 

    % git pull upstream master

Of course make sure you have added upstream as a remote first.

**Comment by lcabrini** [comment]
I'm taking care of this issue.

**Comment by lcabrini** [comment]
Done. Please pull from upstream and verify that all is fine. Then we can close this issue.

**Comment by Prince-linux** [comment]
How do I do this??

**Comment by Prince-linux** [comment]
I have done git pull upstream master

**Comment by lcabrini** [comment]
If you have set up my repo as upstream for your repo, simply do:

    % git pull upstream master

If you haven't you first need to add the upstream:

    % git remote add upstream https://github.com/lcabrini/tsofa.git

**Comment by lcabrini** [comment]
Are there any files left in the laravel directory? If there aren't then you can safely delete the dir. 

If there are any files left in laravel, let me know.

**Comment by Prince-linux** [comment]
I deleted them because they were duplicates

**Comment by Prince-linux** [comment]
done we can close this please
